### ISSUE TITLE
please tag releases

### ISSUE THREAD

**Issue by mschiff** [SethDart/vdr_pi#3]
Hi!

It would be very usefull to have tagged releases, so the source for a specific version of th eplugin can be downloaded. Please add a release/tag for your released versions. This makes packaging a lot easier. 

I'd like to package this plugin for Gentoo Linux and for that it requires a reliable specific download URL for the releases. 

Thanks in advance!

**Comment by mschiff** [comment]
Ping?

**Comment by SethDart** [comment]
Sory for this late reply.

Tagging done!

**Comment by mschiff** [comment]
Thank you! But I cannot see any new release... forgot to push?
