### ISSUE TITLE
!!Master cmake is broken, please merge nohall packaging fork

### ISSUE THREAD

**Issue by dominig** [SethDart/vdr_pi#7]
Master is badly broken it does not build using the standard process as the cmake config is broken.
Please merge in changes from nohal packaging which works.
Thanks.

**Comment by rgleason** [comment]
Pavel's VDR_pi (packaging) Branch works.

https://github.com/nohal/vdr_pi/tree/packaging

**Comment by rgleason** [comment]
Please close,  Current version is in PR here.
